services:
  #Base de datos PostgreSQL
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medusa_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - medusa_network
  #Redis
  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis_container
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    networks:
      - medusa_network
volumes:
  pgdata:
  redisdata:
networks:
  medusa_network:
    driver: bridge
